/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createRootRoute } from '@tanstack/react-router'

import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsProductTablePageRouteImport } from './routes/products/productTablePage'
import { Route as ProductsIdRouteImport } from './routes/products/$id'

const rootRouteImport = createRootRoute()

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductTablePageRoute =
  ProductsProductTablePageRouteImport.update({
    id: '/products/productTablePage',
    path: '/products/productTablePage',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/productTablePage': typeof ProductsProductTablePageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/productTablePage': typeof ProductsProductTablePageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/products/$id': typeof ProductsIdRoute
  '/products/productTablePage': typeof ProductsProductTablePageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/products/$id' | '/products/productTablePage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/products/$id' | '/products/productTablePage'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/products/$id'
    | '/products/productTablePage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsProductTablePageRoute: typeof ProductsProductTablePageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/productTablePage': {
      id: '/products/productTablePage'
      path: '/products/productTablePage'
      fullPath: '/products/productTablePage'
      preLoaderRoute: typeof ProductsProductTablePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsProductTablePageRoute: ProductsProductTablePageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
